import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div>
          <header className="bg-gray-800 text-white px-6 py-6 font-bold flex justify-between items-center">
            <Link href="/" className="ml-4">
              Blog
            </Link>
            <Link href="/contact" className="ml-4">
              お問い合わせ
            </Link>
          </header>
        </div>
        <div className="max-w-3xl mx-auto my-10 px-4">{children}</div>
      </body>
    </html>
  );
}
